name: Lox Acceptance Tests

on: [push]

jobs:
  acceptance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: Swatinem/rust-cache@v1
      - name: Build Brine
        run: cargo build --verbose

      - name: Crafting Interpreters Cache
        id: craftinginterpreters-cache
        uses: actions/cache@v2
        with:
          path: ./craftinginterpreters
          key: craftinginterpreters
          restore-keys: |
            craftinginterpreters

      - name: Dart Binary Cache
        id: dart-cache
        uses: actions/cache@v2
        with:
          path: |
            /opt/hostedtoolcache/dart-sdk/bin
          key: dart-cache
          restore-keys: |
            dart-cache

      - name: Dart Package Cache
        id: dart-pkg-cache
        uses: actions/cache@v2
        with:
          path: |
            /home/runner/.pub-cache
          key: dart-pkg-cache-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            dart-pkg-cache-

      - name: Clone Crafting Intepreters
        if: steps.craftinginterpreters-cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v2
        with:
          repository: munificent/craftinginterpreters
          path: craftinginterpreters

      - uses: dart-lang/setup-dart@v1
        if: steps.dart-cache.outputs.cache-hit != 'true'

      - name: Build Dart Tooling
        if: steps.dart-pkg-cache.outputs.cache-hit != 'true'
        run: make get
        working-directory: craftinginterpreters

      - name: Run acceptance tests
        run: cargo test --test acceptance -- --show-output
        env:
          BINARY_PATH: ./target/debug/brine
          DART_DIR: ./craftinginterpreters
