name: Lox Acceptance Tests

on: [push]

jobs:
  acceptance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: Swatinem/rust-cache@v1
      - name: Build Brine
        run: cargo build --verbose

      - name: Dart Tooling Cache
        id: dart-cache
        uses: actions/cache@v2
        with:
          path: |
            ./craftinginterpreters
            /home/runner/.pub-cache
            /opt/hostedtoolcache/dart-sdk/bin
          key: craftinginterpreters

      - name: Clone Dart
        if: steps.dart-cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v2
        with:
          repository: munificent/craftinginterpreters
          path: craftinginterpreters

      - uses: dart-lang/setup-dart@v1
        if: steps.dart-cache.outputs.cache-hit != 'true'

      - name: Build Dart Tooling
        if: steps.dart-cache.outputs.cache-hit != 'true'
        run: make get
        working-directory: craftinginterpreters

      - name: Run acceptance tests
        run: |
          make get
          dart tool/bin/test.dart chap04_scanning --interpreter /home/runner/work/brine/brine/target/debug/brine
        env:
          BINARY_PATH: ./target/debug/brine
          DART_DIR: ./craftinginterpreters
        working-directory: craftinginterpreters
