name: Lox Acceptance Tests

on: [push]

jobs:
  acceptance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: Swatinem/rust-cache@v1
      - name: Build Brine
        run: cargo build --verbose

      - name: Crafting Interpreters Cache
        id: craftinginterpreters-cache
        uses: actions/cache@v2
        with:
          path: ./craftinginterpreters
          key: craftinginterpreters

      - name: Dart Binary Cache
        id: dart-cache
        uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache/dart-sdk/bin
          key: dart-cache

      - name: Clone Crafting Intepreters
        if: steps.craftinginterpreters-cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v2
        with:
          repository: munificent/craftinginterpreters
          path: craftinginterpreters

      - uses: dart-lang/setup-dart@v1

      - name: Build Dart Tooling
        run: make get
        working-directory: craftinginterpreters

      - name: Run acceptance tests
        run: |
          BINARY_PATH=./target/debug/brine DART_DIR=./craftinginterpreters cargo test --test external_integration -- --show-output
        env:
          BINARY_PATH: ./target/debug/brine
          DART_DIR: ./craftinginterpreters
        working-directory: craftinginterpreters
