name: Lox Acceptance Tests

on: [push]

jobs:
  acceptance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: Swatinem/rust-cache@v1
      - name: Build Brine
        run: cargo build --verbose

      - name: Dart Tooling Cache
        id: dart-cache
        uses: actions/cache@v2
        with:
          path: ./craftinginterpreters
          key: craftinginterpreters

      - name: Clone Dart
        if: steps.dart-cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v2
        with:
            repository: munificent/craftinginterpreters
            path: craftinginterpreters

      - uses: dart-lang/setup-dart@v1
      - name: Build Dart Tooling
        run: make get
        working-directory: craftinginterpreters
