name: Lox Acceptance Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Brine
        uses: Swatinem/rust-cache@v1
        run: cargo build --verbose

      - name: Build dart tooling
        uses: actions/checkout@v2
        with:
          repository: munificent/craftinginterpreters
          path: craftinginterpreters
        uses: dart-lang/setup-dart@v1
        run: make get
        working-directory: craftinginterpreters
