name: Lox Acceptance Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: Swatinem/rust-cache@v1
      - name: Build Brine
        run: cargo build --verbose

      - name: Clone Dart
        uses: actions/checkout@v2
        with:
            repository: munificent/craftinginterpreters
            path: craftinginterpreters

      - uses: dart-lang/setup-dart@v1
      - name: Build Dart Tooling
        run: make get
        working-directory: craftinginterpreters
